[package]
name = "dif-fuzzer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
libafl = "0.14.1"
libafl_bolts = "0.14.1"
log = "0.4.22"
log4rs = "1.3.0"
rand = "0.8.5"
regex = "1.11.1"
serde = "1.0.215"
