# See "diffuzzer/src/config.rs" for documentation

fs_name = "fstest"
heartbeat_interval = 30 # in seconds
max_workload_length = 100
timeout = 10 # in seconds

[qemu]
os_image = "./disk.img" 
direct_boot = false
kernel_image_path = ".../linux-x.xx/arch/x86/boot/bzImage"
root_disk_partition = "/dev/vda1"
launch_script = "./tools/launch-snapshot.sh"
ssh_private_key_path = "./ssh.key"
boot_wait_time = 10 # in seconds
log_path = "./qemu.log"

[greybox]
max_mutations = 10
save_corpus = true
scheduler = "FAST"
m_constant = 10000

[dash]
enabled = true
debug_binary_path = "./target/debug/dash"
release_binary_path = "./target/release/dash"

[operation_weights]
weights = [
  [
    "CREATE",
    100,
  ],
  [
    "MKDIR",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
  [
    "HARDLINK",
    100,
  ],
  [
    "SYMLINK",
    30,
  ],
  [
    "RENAME",
    100,
  ],
  [
    "OPEN",
    100,
  ],
  [
    "CLOSE",
    30,
  ],
  [
    "WRITE",
    100,
  ],
  [
    "READ",
    100,
  ],
  [
    "FSYNC",
    30,
  ],
]

[mutation_weights]
weights = [
  [
    "INSERT",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
]
