count = 100
max_workload_length = 100

[greybox]
heartbeat_interval = 30 # in seconds
max_mutations = 10 
timeout = 10 # in seconds

[operation_weights]
weights = [
  [
    "CREATE",
    100,
  ],
  [
    "MKDIR",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
  [
    "HARDLINK",
    100,
  ],
  [
    "RENAME",
    100,
  ],
  [
    "OPEN",
    100,
  ],
  [
    "CLOSE",
    30,
  ],
]

[mutation_weights]
weights = [
  [
    "INSERT",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
]



