fs_name = "fstest" 
hashing_enabled = false 
heartbeat_interval = 30 # in seconds
max_workload_length = 100 
timeout = 10 # in seconds

[qemu_config]
ssh_private_key_path = "./ssh_key"

[qemu_config.launch_options]
cmd = "qemu-system-x86_64"
cpu = "host"
drive = {if = "virtio", format = "qcow2", file = "./disk.img"}
extra = [
  "-nographic",
  "-enable-kvm",
  "-snapshot",
]
machine = {accel = "kvm", type = "q35"}
memory = "2G"
monitor_port = "55555"
netdev_ssh_forward_port = "2222"
smp = {cores = "2"}

[greybox]
max_mutations = 10
save_corpus = false

[operation_weights]
weights = [
  [
    "CREATE",
    100,
  ],
  [
    "MKDIR",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
  [
    "HARDLINK",
    100,
  ],
  [
    "RENAME",
    100,
  ],
  [
    "OPEN",
    100,
  ],
  [
    "CLOSE",
    30,
  ],
  [
    "WRITE",
    100,
  ],
  [
    "READ",
    100,
  ],
  [
    "FSYNC",
    30,
  ],
]

[mutation_weights]
weights = [
  [
    "INSERT",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
]
