[operation_weights]

weights = [
  [
    "CREATE",
    100,
  ],
  [
    "MKDIR",
    100,
  ],
  [
    "REMOVE",
    100,
  ],
]

[mutation_weights]

weights = [
  [
    "INSERT",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
]
