[greybox]
max_workload_length = 100
max_mutations = 10
timeout = 10 # in seconds
heartbeat_interval = 30 # in seconds

[operation_weights]
weights = [
  [
    "CREATE",
    100,
  ],
  [
    "MKDIR",
    100,
  ],
  [
    "REMOVE",
    100,
  ],
  [
    "HARDLINK",
    100,
  ],
  [
    "RENAME",
    100,
  ],
]

[mutation_weights]
weights = [
  [
    "INSERT",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
]
