fs_name = "fstest" 
hashing_enabled = false 
heartbeat_interval = 30 # in seconds
max_workload_length = 100 
timeout = 10 # in seconds

[greybox]
max_mutations = 10
save_corpus = false

[operation_weights]
weights = [
  [
    "CREATE",
    100,
  ],
  [
    "MKDIR",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
  [
    "HARDLINK",
    100,
  ],
  [
    "RENAME",
    100,
  ],
  [
    "OPEN",
    100,
  ],
  [
    "CLOSE",
    30,
  ],
  [
    "WRITE",
    100,
  ],
  [
    "READ",
    100,
  ],
]

[mutation_weights]
weights = [
  [
    "INSERT",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
]
