fs_name = "fstest" 
dash_enabled = false 
heartbeat_interval = 30 # in seconds
max_workload_length = 100 
timeout = 10 # in seconds

[qemu]
launch_script = "./tools/launch-snapshot.sh"
monitor_port = 55555
os_image = "./disk.img"
ssh_port = 2222
ssh_private_key_path = "./ssh.key"
boot_wait_time = 10 # in seconds
log_path = "./qemu.log"
monitor_socket_path = "/tmp/diffuzzer-qemu-monitor.sock"
qmp_socket_path = "/tmp/diffuzzer-qemu-qmp.sock"

[greybox]
max_mutations = 10
save_corpus = false

[operation_weights]
weights = [
  [
    "CREATE",
    100,
  ],
  [
    "MKDIR",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
  [
    "HARDLINK",
    100,
  ],
  [
    "RENAME",
    100,
  ],
  [
    "OPEN",
    100,
  ],
  [
    "CLOSE",
    30,
  ],
  [
    "WRITE",
    100,
  ],
  [
    "READ",
    100,
  ],
  [
    "FSYNC",
    30,
  ],
]

[mutation_weights]
weights = [
  [
    "INSERT",
    100,
  ],
  [
    "REMOVE",
    30,
  ],
]
